# Generated by Django 5.2 on 2025-04-21 16:06

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('hinh_dai_dien', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NguoiTimViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gioi_tinh', models.BooleanField()),
                ('ngay_sinh', models.DateTimeField()),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('ky_nang', models.CharField(max_length=255)),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_tim_viec', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_dai_dien', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('ho_ten', models.CharField(max_length=255)),
                ('nghe_nghiep_ung_tuyen', models.CharField(max_length=255)),
                ('bang_cap_cao_nhat', models.CharField(max_length=255)),
                ('so_nam_kinh_nghiem', models.IntegerField()),
                ('so_dien_thoai', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('khu_vuc_lam_viec', models.CharField(max_length=255)),
                ('dia_chi_chi_tiet', models.CharField(max_length=255)),
                ('gioi_tinh', models.BooleanField()),
                ('muc_luong_mong_muon', models.IntegerField()),
                ('linkedln', models.URLField()),
                ('muc_tieu_nghe_nghiep', models.TextField()),
                ('ky_nang', models.CharField(max_length=255)),
                ('thanh_tich', models.CharField(max_length=255)),
                ('chung_nhan', models.CharField(max_length=255)),
                ('so_thich', models.CharField(max_length=255)),
                ('qua_trinh_hoat_dong', models.CharField(max_length=255)),
                ('nguoi_tim_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='careers.nguoitimviec')),
            ],
        ),
        migrations.CreateModel(
            name='NhaTuyenDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_doanh_nghiep', models.CharField(max_length=255)),
                ('website_doanh_nghiep', models.URLField()),
                ('gioi_thieu_doanh_nghiep', models.TextField()),
                ('linh_vuc_hoat_dong', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(max_length=255)),
                ('hinh_anh_doanh_nghiep', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nha_tuyen_dung', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoiThoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField()),
                ('thoi_gian_ket_thuc', models.DateTimeField()),
                ('nguoi_tim_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.nguoitimviec')),
                ('nha_tuyen_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.nhatuyendung')),
            ],
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_doc', models.BooleanField()),
                ('noi_dung', models.TextField()),
                ('thoi_gian_gui_tin', models.DateTimeField()),
                ('hoi_thoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.hoithoai')),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViecLam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenCongViec', models.CharField(max_length=255)),
                ('viTriDangTuyen', models.CharField(max_length=255)),
                ('kinhNghiem', models.DateTimeField()),
                ('mucLuong', models.IntegerField()),
                ('diaChi', models.CharField(max_length=255)),
                ('soLuongTuyen', models.IntegerField()),
                ('doTuoi', models.IntegerField()),
                ('hinhThucLamViec', models.CharField(max_length=50)),
                ('bangCap', models.CharField(max_length=50)),
                ('phucLoi', models.TextField()),
                ('noiDungCongViec', models.TextField()),
                ('yeuCauCongViec', models.TextField()),
                ('thongTinLienHe', models.CharField(max_length=255)),
                ('ngayTao', models.DateTimeField(auto_now_add=True)),
                ('ngayCapNhat', models.DateTimeField(auto_now=True)),
                ('ngayHetHan', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('nha_tuyen_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viec_lam', to='careers.nhatuyendung')),
            ],
        ),
        migrations.CreateModel(
            name='YeuCauTuyenDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_ung_tuyen', models.DateTimeField(auto_now_add=True)),
                ('ngay_cat_nhat', models.DateTimeField(auto_now=True)),
                ('danh_gia_ho_so', models.CharField(max_length=255, null=True)),
                ('ket_qua_ho_so', models.BooleanField()),
                ('ket_qua_tuyen_dung', models.BooleanField()),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='careers.cv')),
                ('nguoi_tim_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.nguoitimviec')),
                ('viec_lam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.vieclam')),
            ],
            options={
                'verbose_name': 'Yêu cầu tuyển dụng',
                'verbose_name_plural': 'Các yêu cầu tuyển dụng',
                'unique_together': {('nguoi_tim_viec', 'viec_lam')},
            },
        ),
        migrations.CreateModel(
            name='PhongVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_phong_van', models.DateTimeField()),
                ('video_URL', models.URLField()),
                ('danh_gia', models.TextField()),
                ('ket_qua_phong_van', models.BooleanField()),
                ('yeu_cau_phong_van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.yeucautuyendung')),
            ],
        ),
    ]
