# Generated by Django 5.1.7 on 2025-04-18 08:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoitimviec',
            name='email',
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='hinh_dai_dien',
            field=cloudinary.models.CloudinaryField(default='https://media.istockphoto.com/id/1337144146/vector/default-avatar-profile-icon-vector.jpg?s=612x612&w=0&k=20&c=BIbFwuv7FxTWvh5S3vB6bkT0Qv8Vn8N5Ffseq84ClGI=', max_length=255, verbose_name='hinh_dai_dien'),
        ),
        migrations.AlterField(
            model_name='nhatuyendung',
            name='hinh_anh_doanh_nghiep',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='hinh_dai_doanh_nghiep'),
        ),
    ]
