# Generated by Django 5.2 on 2025-04-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeucautuyendung',
            name='ngay_cat_nhat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
