# Generated by Django 5.1.7 on 2025-04-18 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_remove_nguoitimviec_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhatuyendung',
            old_name='gioi_thieu_doanh_nghiep',
            new_name='gioi_thieu',
        ),
        migrations.RenameField(
            model_name='nhatuyendung',
            old_name='linh_vuc_hoat_dong',
            new_name='linh_vuc',
        ),
        migrations.RemoveField(
            model_name='nhatuyendung',
            name='hinh_anh_doanh_nghiep',
        ),
        migrations.RemoveField(
            model_name='nhatuyendung',
            name='website_doanh_nghiep',
        ),
        migrations.AddField(
            model_name='nguoitimviec',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nhatuyendung',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='nhatuyendung',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='hinh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='vai_tro',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nguoitimviec',
            name='ky_nang',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nguoitimviec',
            name='ngay_sinh',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nguoitimviec',
            name='nguoi_dung',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nguoitimviec',
            name='so_dien_thoai',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nhatuyendung',
            name='nguoi_dung',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_dai_dien', models.ImageField(blank=True, null=True, upload_to='cv_photos/')),
                ('ho_ten', models.CharField(max_length=255)),
                ('nghe_nghiep_ung_tuyen', models.CharField(max_length=255)),
                ('bang_cap', models.CharField(choices=[('THPT', 'Trung học phổ thông'), ('CAO_DANG', 'Cao đẳng'), ('DAI_HOC', 'Đại học'), ('THAC_SI', 'Thạc sĩ'), ('TIEN_SI', 'Tiến sĩ')], max_length=30)),
                ('so_nam_kinh_nghiem', models.IntegerField()),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('khu_vuc', models.CharField(max_length=255)),
                ('dia_chi_chi_tiet', models.TextField()),
                ('gioi_tinh', models.BooleanField()),
                ('muc_luong_mong_muon', models.IntegerField()),
                ('linkedin', models.URLField(blank=True)),
                ('muc_tieu_nghe_nghiep', models.TextField()),
                ('kinh_nghiem', models.TextField()),
                ('ky_nang', models.TextField()),
                ('thanh_tich', models.TextField(blank=True)),
                ('chung_nhan', models.TextField(blank=True)),
                ('so_thich', models.TextField(blank=True)),
                ('hoat_dong', models.TextField(blank=True)),
                ('thong_tin_khac', models.TextField(blank=True)),
                ('nguoi_tim_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.nguoitimviec')),
            ],
        ),
        migrations.CreateModel(
            name='HoiThoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField(auto_now_add=True)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('nguoi1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi1', to=settings.AUTH_USER_MODEL)),
                ('nguoi2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_gui', to=settings.AUTH_USER_MODEL)),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_nhan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViecLam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('vi_tri', models.CharField(max_length=255)),
                ('kinh_nghiem', models.DurationField()),
                ('muc_luong', models.IntegerField()),
                ('dia_chi', models.CharField(max_length=255)),
                ('so_luong_tuyen', models.IntegerField()),
                ('do_tuoi', models.IntegerField()),
                ('hinh_thuc', models.CharField(choices=[('TOAN_THOI_GIAN', 'Toàn thời gian'), ('BAN_THOI_GIAN', 'Bán thời gian'), ('THUC_TAP', 'Thực tập'), ('FREELANCE', 'Freelance')], max_length=30)),
                ('bang_cap', models.CharField(choices=[('THPT', 'Trung học phổ thông'), ('CAO_DANG', 'Cao đẳng'), ('DAI_HOC', 'Đại học'), ('THAC_SI', 'Thạc sĩ'), ('TIEN_SI', 'Tiến sĩ')], max_length=30)),
                ('phuc_loi', models.TextField()),
                ('noi_dung', models.TextField()),
                ('yeu_cau', models.TextField()),
                ('lien_he', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('ngay_het_han', models.DateTimeField()),
                ('duyet', models.BooleanField(default=False)),
                ('nha_tuyen_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.nhatuyendung')),
            ],
        ),
        migrations.CreateModel(
            name='YeuCauTuyenDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_ung_tuyen', models.DateTimeField(auto_now_add=True)),
                ('danh_gia', models.TextField(blank=True)),
                ('ket_qua_ho_so', models.BooleanField(default=False)),
                ('ket_qua_tuyen_dung', models.BooleanField(default=False)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.cv')),
                ('viec_lam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.vieclam')),
            ],
        ),
        migrations.CreateModel(
            name='PhongVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField()),
                ('video_url', models.URLField()),
                ('danh_gia', models.TextField(blank=True)),
                ('ket_qua', models.BooleanField(default=False)),
                ('yeu_cau', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='careers.yeucautuyendung')),
            ],
        ),
    ]
