# Generated by Django 5.2 on 2025-04-20 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_yeucautuyendung_ngay_cat_nhat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thongbao',
            name='nguoi_dung',
        ),
        migrations.AddField(
            model_name='thongbao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NguoiDungXemThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_xem_gan_nhat', models.DateTimeField(auto_now=True)),
                ('da_doc', models.BooleanField(default=False)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thong_bao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.thongbao')),
            ],
            options={
                'unique_together': {('nguoi_dung', 'thong_bao')},
            },
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='xem_thong_bao',
            field=models.ManyToManyField(through='careers.NguoiDungXemThongBao', to='careers.thongbao'),
        ),
    ]
