# Generated by Django 5.1.7 on 2025-04-18 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_rename_gioi_thieu_doanh_nghiep_nhatuyendung_gioi_thieu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='khu_vuc',
            new_name='khu_vuc_lam_viec',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='nghe_nghiep_ung_tuyen',
            new_name='nghe_nghiep',
        ),
        migrations.RenameField(
            model_name='nhatuyendung',
            old_name='linh_vuc',
            new_name='linh_vuc_hoat_dong',
        ),
        migrations.RenameField(
            model_name='thongbao',
            old_name='thoi_gian',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tinnhan',
            old_name='thoi_gian',
            new_name='thoi_gian_gui_tin',
        ),
        migrations.RenameField(
            model_name='vieclam',
            old_name='lien_he',
            new_name='mo_ta',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='dia_chi_chi_tiet',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='gioi_tinh',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='hinh_dai_dien',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='hoat_dong',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='kinh_nghiem',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='hoithoai',
            name='nguoi1',
        ),
        migrations.RemoveField(
            model_name='hoithoai',
            name='nguoi2',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='vai_tro',
        ),
        migrations.RemoveField(
            model_name='vieclam',
            name='hinh_thuc',
        ),
        migrations.RemoveField(
            model_name='vieclam',
            name='noi_dung',
        ),
        migrations.AddField(
            model_name='cv',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cv',
            name='dia_chi',
            field=models.CharField(default='Chưa cập nhật', max_length=255),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='da_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tinnhan',
            name='hoi_thoai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to='careers.hoithoai'),
        ),
        migrations.AddField(
            model_name='tinnhan',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vieclam',
            name='hinh_thuc_lam_viec',
            field=models.CharField(choices=[('FT', 'Toàn thời gian'), ('PT', 'Bán thời gian'), ('TT', 'Thực tập'), ('FR', 'Freelance')], default='FT', max_length=10),
        ),
        migrations.AlterField(
            model_name='cv',
            name='bang_cap',
            field=models.CharField(choices=[('TC', 'Trung cấp'), ('CD', 'Cao đẳng'), ('DH', 'Đại học'), ('TS', 'Thạc sĩ'), ('TSI', 'Tiến sĩ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cv',
            name='muc_luong_mong_muon',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='so_nam_kinh_nghiem',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='nguoitimviec',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nguoitimviec',
            name='gioi_tinh',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='nguoitimviec',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nhatuyendung',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='phongvan',
            name='danh_gia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='phongvan',
            name='ket_qua',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tinnhan',
            name='nguoi_gui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_gui', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tinnhan',
            name='nguoi_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vieclam',
            name='bang_cap',
            field=models.CharField(choices=[('TC', 'Trung cấp'), ('CD', 'Cao đẳng'), ('DH', 'Đại học'), ('TS', 'Thạc sĩ'), ('TSI', 'Tiến sĩ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vieclam',
            name='do_tuoi',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vieclam',
            name='muc_luong',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vieclam',
            name='so_luong_tuyen',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='yeucautuyendung',
            name='ket_qua_ho_so',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='yeucautuyendung',
            name='ket_qua_tuyen_dung',
            field=models.BooleanField(null=True),
        ),
    ]
