# Generated by Django 5.1.7 on 2025-04-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_rename_khu_vuc_cv_khu_vuc_lam_viec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
