# Generated by Django 5.1.7 on 2025-04-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_alter_cv_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatuyendung',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='static/logos/'),
        ),
    ]
