# Generated by Django 5.1.7 on 2025-04-19 04:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_alter_nhatuyendung_hinh_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatuyendung',
            name='gioi_thieu',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='nhatuyendung',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
