# Generated by Django 5.1.7 on 2025-04-19 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_alter_nhatuyendung_gioi_thieu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thongbao',
            name='nguoi_dung',
        ),
        migrations.CreateModel(
            name='NguoiDungXemThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_xem_gan_nhat', models.DateTimeField(auto_now=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thong_bao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.thongbao')),
            ],
            options={
                'unique_together': {('nguoi_dung', 'thong_bao')},
            },
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='xem_thong_bao',
            field=models.ManyToManyField(through='careers.NguoiDungXemThongBao', to='careers.thongbao'),
        ),
    ]
