# Generated by Django 5.1.7 on 2025-04-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_remove_thongbao_nguoi_dung_nguoidungxemthongbao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thongbao',
            name='da_doc',
        ),
        migrations.AddField(
            model_name='nguoidungxemthongbao',
            name='da_doc',
            field=models.BooleanField(default=False),
        ),
    ]
